### PR TITLE
Improve Chat Screen UI

### PR DESCRIPTION
**Pull request by ChesterSim**
Improve Chat Screen UI

### CODE REVIEW

**Comment by ChesterSim** [comment]
Implement #39

**Comment by ChesterSim** [comment]
Sorry Robin, I understand that you wanted each issue to be a different PR. However, because I created the PR from my own repo, every time I commit, it will automatically update this PR when it has not been approved

**Comment by robinloh** [comment]
For your code implementation of features, you have been committing to the master branch. This is the problem. You should not be relying on 1 branch for all features implementation. For any new feature, you should branch out first, so that when you create PRs, you can actually select that branch to merge into `clique-orbital:master`.

**Comment by robinloh** [comment]
Instead of 1 single PR (#38), open 3 PRs for the 3 changes, namely improve UX, remove testing poll button, system message for accepting invitation)

**Pull request closed without merging**
